# Data Settings
data:
  root_dir: '/Users/pesala/Documents/brats_dataset_short/brats_dataset_short'
  seed : 42
  class_labels:
    Healthy: 0
    # LGG: 2
    HGG: 1
  batch_size: 4

# Model Settings
model:
  num_classes: 2
  input_shape: (1, 155, 240, 240)  # Format: (C, D, H, W)
  dropout_prob: 0.5
  # available architectures are MobilenetV2_3D, Simple3dCNN, Resnet3D
  architecture: "MobilenetV2_3D"
  #criterion: "CrossEntropyLoss"
  # available optimizers are sgd, adam
  optimizer: "sgd"

# Training Settings
training:
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.01
  num_epochs: 40
  scheduler_patience: 3
  scheduler_factor: 0.05
  patience: 5

# Wandb 
wandb:
  project: "Brain Tumor Classification"
  entity: "thesis-htwsaar"
  run_name: "MobilenetV2_final"