# Data Settings
data:
  root_dir: "path_to_the_root_directory"
  seed : 42
  class_labels:
    Healthy: 0
    LGG: 1
    HGG: 2
  batch_size: 2

# Model Settings
model:
  num_classes: 3
  input_shape: (1, 155, 240, 240)  #Format: (C, D, H, W)
  dropout_prob: 0.5
  architecture: "MobileNetV2"     # available architectures: MobilenetV2_3D, Resnet3D
  criterion: "CrossEntropyLoss"
  optimizer: "adam"               # available optimizers are sgd, adam

# Training Settings
training:
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.05
  num_epochs: 40
  scheduler_patience: 4
  scheduler_factor: 0.05
  patience: 5

# Wandb 
wandb:
  project: "Brain Tumor Classification"
  entity: "thesis-htwsaar"
  run_name: "MobilenetV2"











